version = 0.1

[default.global.parameters]
stack_name = "kickbi-backend"
resolve_s3 = true

[dev.deploy.parameters]
stack_name = "kickbi-backend-dev"
s3_bucket = "kickbi-dev-deployments"
s3_prefix = "kickbi-backend-dev"
region = "ap-south-1"
profile = "kickbi-dev"
parameter_overrides = "Stage=dev"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"

[dev.delete.parameters]
stack_name = "kickbi-backend-dev"
region = "ap-south-1"
profile = "kickbi-dev"

[prod.deploy.parameters]
stack_name = "kickbi-backend-prod"
resolve_s3 = true
region = "ap-south-1"
profile = "kickbi-prod"
parameter_overrides = "Stage=prod"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

[prod.delete.parameters]
stack_name = "kickbi-backend-prod"
region = "ap-south-1"
profile = "kickbi-prod"
